### ISSUE TITLE
Signals with Arguments

### ISSUE THREAD

**Issue by lishaduck** [tc39/proposal-signals#228]
When writing code that uses Preact signals, I often miss [Riverpod's family providers](https://riverpod.dev/docs/essentials/passing_args) from Dart.
This is a feature that allows signals to be parameterized. I find this to be an essential feature, as it allows computing state on demand, like `Computed`, but which depends on data. As an example from Riverpod's docs, you might want to store the response from a request, so you use `Computed` to make and store the request, but if you need to make the request not constant, you're out of luck. If this signal is just for one component, it might be fine to couple it so, but it prevents making more general-purpose signals.
It's my understanding that this is what Starlight's [_optionally reactive arguments_](https://www.starbeamjs.com/guides/fundamentals/functions.html#optionally-reactive-arguments) do from a quick glance, although I might be wrong.

Alternatively, you can use a `Map` and log it in there, but then it isn't reactive. Or, you can save the parameters as other signals and depend on them on the signal, but that gets very brittle very quickly. Maybe I'm missing something, but I can't figure out a way to write this style of code, and have ended up just refactoring my code to be less reactive, which is saddening.

Apologies if this has been discussed elsewhere, but I didn't see any issues with similar titles.

Links:
- <https://riverpod.dev/docs/concepts/modifiers/family>
- <https://riverpod.dev/docs/essentials/passing_args>
- <https://riverpod.dev/docs/concepts/about_code_generation#passing-parameters-to-a-provider-family>

**Comment by shaylew** [comment]
The primitives in the proposal are intended to be sufficient for building this kind of library, for sure. I haven't implemented that API so I'm not sure what the snags might be, but it seems like you should be able to put ordinary Computeds in a Map to create a "family of computeds", with the library's wrapper just populating the map lazily if the family member that was being asked for doesn't exist yet. 

The thing makes this tricky to have in the core (rather than in a library) is that you have to make a bunch of decisions about cleanups, lifecycle, and memory tradeoffs here. If arguments are always objects you can use a weak map, but otherwise the library has to decide how long to keep a Computed in the map and when to decide it's no longer in use and should be thrown away. Things like the `unwatched` callback can be building blocks here, but family-style libraries have made different choices about these details and we'd rather let them keep the choices that work for them (while building on a shared signals foundation) than try to make a binding decision on those tradeoffs part of the standard.
